channels:
  - conda-forge
  - defaults
dependencies:
- geopandas
- pyworms
- ckanapi
- httpx
- plotly
- cartopy
- async
- requests
- numpy
- pytest
- pandas>=2.0.0
- pip
- pip:
  - pyxylookup
  - asyncio
  - httpx
